# -*- coding: utf-8 -*-
"""
Regenerate app/portal/data.js from the LIVE Google Sheets.

Reads each source sheet with a Google **service account** (Drive export → xlsx),
runs the same parsers used to build the dashboards, and stitches their output into
one data.js. The GitHub Action (.github/workflows/refresh-data.yml) runs this on a
schedule and commits the result, so Vercel redeploys with fresh numbers.

Env:
  GOOGLE_SERVICE_ACCOUNT_JSON  – the full service-account key JSON (as a string).
                                 The service account email must have VIEW access to
                                 each sheet below.

Covers: Weight, Sales, FE Tracker, Engagement & Retention.
(LTV Opportunity data is currently embedded in the UI; its parser is a follow-up.)
"""
import os, sys, io, json, subprocess
import requests
from google.oauth2 import service_account
from google.auth.transport.requests import Request

XLSX = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'

# filename the parser expects  →  Google Sheet id
SHEETS = {
    'weight.xlsx': '1gb6zP4GzcgM8hjS1muRbEo3wh4a7sbOeApmvT2H9kwA',
    'sales.xlsx':  '1FlY3urpuhvC9HSQczeXCacWilujJxr308uHg16O3xQU',
    'fe.xlsx':     '1VVFE_wq5Q1XdZBG_fBu0PJ7ogHbfBv_PTypxl9oc048',
    'ret.xlsx':    '1O6EGA833uz8OdJcI9L7Axdbqm_lAEKLvj4E-oHvlHp8',
    'ltv.xlsx':    '1hifgKA-h_cJARz6ZkGBRT_E8FtIlDpgk61juli5lFSY',
}
PARSERS = ['parse_weight.py', 'parse_sales.py', 'parse_fe.py', 'parse_ret.py', 'parse_ltv.py']
# concatenated in this order into data.js (order is irrelevant at runtime)
OUTPUTS = ['aug_data.js', 'med_data.js', 'coach_data.js', 'mom_data.js',
           'sales_data.js', 'fe_data.js', 'ret_data.js', 'ltv_data.js']


def credentials():
    raw = os.environ.get('GOOGLE_SERVICE_ACCOUNT_JSON')
    if not raw:
        sys.exit('GOOGLE_SERVICE_ACCOUNT_JSON is not set.')
    info = json.loads(raw)
    creds = service_account.Credentials.from_service_account_info(
        info, scopes=['https://www.googleapis.com/auth/drive.readonly'])
    creds.refresh(Request())
    return creds


def download(creds, file_id, out):
    r = requests.get(
        f'https://www.googleapis.com/drive/v3/files/{file_id}/export',
        params={'mimeType': XLSX},
        headers={'Authorization': 'Bearer ' + creds.token},
        timeout=180,
    )
    r.raise_for_status()
    with open(out, 'wb') as f:
        f.write(r.content)
    print(f'  ↓ {out}  ({len(r.content):,} bytes)')


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    os.chdir(here)

    print('Authenticating service account…')
    creds = credentials()

    print('Downloading sheets…')
    for out, fid in SHEETS.items():
        download(creds, fid, out)

    print('Parsing…')
    for p in PARSERS:
        print(f'  • {p}')
        subprocess.run([sys.executable, p], check=True)

    parts = [io.open(f, encoding='utf-8').read().strip() for f in OUTPUTS]
    data = ('/* Dashboard data — regenerated by scripts/refresh_data.py. Do not hand-edit. */\n'
            + '\n'.join(parts) + '\n')
    dst = os.path.join(here, '..', 'app', 'portal', 'data.js')
    io.open(dst, 'w', encoding='utf-8').write(data)
    print(f'Wrote {dst}  ({len(data):,} bytes)')


if __name__ == '__main__':
    main()
